# Generated by Django 3.1.7 on 2021-03-31 21:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Название')),
                ('attach', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='sign'), upload_to='')),
            ],
        ),
    ]
